twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        nom: '%nom_dev%'
        adresse: '%adresse_dev%'
        ville: '%ville_dev%'
        mail: '%mail_dev%'
        locales: '%app_locales%'
    form_themes: ['bootstrap_4_layout.html.twig']
